services:
  ollama:
    image: "ollama/ollama"
    ports:
      - "11434:11434"
    volumes:
      - /storage/ollama:/root/.ollama
    entrypoint: ["/usr/bin/bash", "-c", "/bin/ollama serve & sleep 5; ollama pull deepseek-r1:1.5b; wait"]

  oracle:
    image: "ghcr.io/matevz/demo-rofl-chatbot:latest"
    environment:
      CONTRACT_ADDRESS: 0xD20Bea4e8CA596891ed2c97fdEca86aF7821aCC1
    entrypoint: /bin/sh -c 'python main.py --network https://testnet.sapphire.oasis.io --ollama-address http://ollama:11434 $${CONTRACT_ADDRESS}'
    restart: on-failure
